//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : BuscarBD.java
//  @ Date : 17-07-2009
//  @ Author : 
//
//




public class BuscarBD {
	public void buscarCliente(Object String parametro) {
	
	}
	
	public void buscarUsuario(Object String parametro) {
	
	}
	
	public void buscarMascota(Object String parametro) {
	
	}
	
	public void buscarFicha(Object String parametro) {
	
	}
	
	public void buscarRegistro(Object String parametro) {
	
	}
	
	public void buscarProducto(Object String parametro) {
	
	}
	
	public void buscarCatalogo(Object String parametro) {
	
	}
	
	public void buscarAviso(Object String parametro) {
	
	}
}
