
import java.util.ArrayList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Hoteleria.java
//  @ Date : 14-07-2009
//  @ Author : 
//
//




public class Hoteleria extends Servicio{
    private ArrayList <Canil> caniles;
    private ArrayList <RegistroHoteleria> registros;

    public Hoteleria(){
        this.caniles = new ArrayList();
        this.registros = new ArrayList();
    }
	public <Canil>ArrayList getCaniles() {
        return this.caniles;
	}
	
	public void addCanil(Canil c) {
        this.caniles.add(c);
	}
	
	public void delCanil(Canil c) {
        for(int i=0;i<caniles.size();i++){
            if(caniles.get(i).getId()==c.getId())
                caniles.remove(i);
        }
	}
	
	public ArrayList <RegistroHoteleria> getRegistrosHoteleria() {
        return this.registros;
	}
	
	public void addRegistroHoteleria(RegistroHoteleria r) {
        this.registros.add(r);
	}
	
	public void delRegistroHoteleria(RegistroHoteleria r) {
        for(int i=0;i<registros.size();i++){
            if(registros.get(i).getId()==r.getId())
                registros.remove(i);
        }
	}
}
