//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MantenerCliente.java
//  @ Date : 17-07-2009
//  @ Author : 
//
//




public class MantenerCliente {
	public void addCliente(Object Cliente c) {
	
	}
	
	public void delCliente(Object int c) {
	
	}
	
	public void purgCliente(Object int c) {
	
	}
	
	public void setCliente(Object Cliente c) {
	
	}
	
	public void getCliente(Object int id) {
	
	}
}
