//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Peluqueria.java
//  @ Date : 17-07-2009
//  @ Author : 
//
//




public class Peluqueria extends Servicio {
	public void getCatalogos() {
	
	}
	
	public void addCatalogo(Object Catalogo c) {
	
	}
	
	public void delCatalogo(Object int i) {
	
	}
	
	public void getRegistroPeluqueria() {
	
	}
	
	public void addRegistroPeluqueria(Object RegistroPeluqueria p) {
	
	}
	
	public void delRegistroPeluqueria(Object int i) {
	
	}
}
