//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : RegistroPeluqueria.java
//  @ Date : 17-07-2009
//  @ Author : 
//
//




public class RegistroPeluqueria extends Registro {
	private int tipo;
	private String comentario;
	public void getTipo() {
	
	}
	
	public void setTipo(Object int t) {
	
	}
	
	public void getComentario() {
	
	}
	
	public void setComentario(Object String c) {
	
	}
}
