//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MantenerRegistro.java
//  @ Date : 17-07-2009
//  @ Author : 
//
//




public class MantenerRegistro {
	public void addRegistro(Object Registro r) {
	
	}
	
	public void delRegistro(Object int id) {
	
	}
	
	public void setRegistro(Object Registro r) {
	
	}
	
	public void getRegistro(Object int id) {
	
	}
}
