//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Pago.java
//  @ Date : 17-07-2009
//  @ Author : 
//
//




public class Pago extends Registro {
	private int monto;
	private Boolean estado;
	public void setMonto(Object int m) {
	
	}
	
	public void getMonto() {
	
	}
	
	public void getEstado() {
	
	}
	
	public void setEstado(Object Boolean e) {
	
	}
}
