//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PetShop.java
//  @ Date : 17-07-2009
//  @ Author : 
//
//




public class PetShop extends Servicio {
	public void calcularPrecio(Object Fecha f, Object int idMascota) {
	
	}
	
	public void addProducto(Object Producto p) {
	
	}
	
	public void delProducto(Object int i) {
	
	}
	
	public void getProductos() {
	
	}
	
	public void addPago(Object Pago p) {
	
	}
	
	public void delPago(Object int i) {
	
	}
	
	public void getPagos() {
	
	}
}
