//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Atencion.java
//  @ Date : 17-07-2009
//  @ Author : 
//
//




public class Atencion extends Registro, Registro {
	private int categoria;
	private int tipo;
	public void getTipo() {
	
	}
	
	public void getCategoria() {
	
	}
	
	public void setTipo(Object int t) {
	
	}
	
	public void setCategoria(Object int t) {
	
	}
}
