//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Catalogo.java
//  @ Date : 17-07-2009
//  @ Author : 
//
//




public class Catalogo extends Registro {
	private String descripcion;
	private Date fechaInicio;
	private int idServicio;
	private Date fechaFin;
	private String tipoAnimal;
	private int id;
	public void setIdServicio(Object int id) {
	
	}
	
	public void getIdServicio() {
	
	}
	
	public void setId(Object int id) {
	
	}
	
	public void getId() {
	
	}
	
	public void getDescripcion() {
	
	}
	
	public void setDescripcion(Object String d) {
	
	}
	
	public void getFechaInicio() {
	
	}
	
	public void setFechaInicio(Object Date i) {
	
	}
	
	public void getFechaFin() {
	
	}
	
	public void setFechaFin(Object Date f) {
	
	}
	
	public void getTipoAnimal() {
	
	}
	
	public void setTipoAnimal(Object String t) {
	
	}
}
