//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Cirugia.java
//  @ Date : 17-07-2009
//  @ Author : 
//
//




public class Cirugia extends Registro {
	private String tipoCirugia;
	private String veterinarioAsociado;
	private String ayudanteAsociado;
	private String estadoOperacion;
	private String diagnostico;
	public void getTipoCirugia() {
	
	}
	
	public void getVeterinario() {
	
	}
	
	public void getAyudante() {
	
	}
	
	public void getEstado() {
	
	}
	
	public void getDiagnostico() {
	
	}
	
	public void setTipoCirugia(Object String c) {
	
	}
	
	public void setVeterinario(Object String v) {
	
	}
	
	public void setAyudante(Object String a) {
	
	}
	
	public void setEstado(Object String e) {
	
	}
	
	public void setDiagnostico(Object String d) {
	
	}
}
