//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Buscar.java
//  @ Date : 17-07-2009
//  @ Author : 
//
//




public class Buscar {
	public void buscarCliente(Object int id, Object int rut, Object string correo, Object int telefono, Object String nombre) {
	
	}
	
	public void buscarUsuario(Object int id, Object String nombre) {
	
	}
	
	public void buscarMascota(Object int id, Object String raza, Object String nombre) {
	
	}
	
	public void buscarFicha(Object int id, Object int idMascota, Object String nombreMascota) {
	
	}
	
	public void buscarRegistro(Object int id, Object int tipo) {
	
	}
	
	public void buscarProducto(Object int id, Object String nombre) {
	
	}
	
	public void buscarCatalogo(Object int id) {
	
	}
	
	public void buscarAviso(Object String id, Object String nombreDueño, Object int rut, Object int telefono) {
	
	}
}
