//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : GestionarConexion.java
//  @ Date : 17-07-2009
//  @ Author : 
//
//




public class GestionarConexion {
}
