//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MantenerFicha.java
//  @ Date : 17-07-2009
//  @ Author : 
//
//




public class MantenerFicha {
	public void addFicha(Object Ficha f) {
	
	}
	
	public void setFicha(Object Ficha f) {
	
	}
	
	public void purgFicha(Object int id) {
	
	}
	
	public void getFicha(Object int id) {
	
	}
}
