//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Pabellon.java
//  @ Date : 17-07-2009
//  @ Author : 
//
//




public class Pabellon extends Servicio {
	public void getPreOperatorios() {
	
	}
	
	public void getCirugias() {
	
	}
	
	public void getPostOperatorio() {
	
	}
	
	public void delPreOperatorio(Object int) {
	
	}
	
	public void delPostOperatorio(Object int) {
	
	}
	
	public void delCirugia(Object int i) {
	
	}
	
	public void addPreOperatorio(Object Registro r) {
	
	}
	
	public void addPostOperatorio(Object Registro r) {
	
	}
	
	public void addCirugia(Object Registro r) {
	
	}
}
