//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SesionUsuario.java
//  @ Date : 17-07-2009
//  @ Author : 
//
//




public class SesionUsuario {
	public void validarUsuario(Object String nombre, Object String contraseña) {
	
	}
}
