//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Producto.java
//  @ Date : 17-07-2009
//  @ Author : 
//
//




public class Producto {
	private int id;
	private String nombre;
	private int precio;
	private String descripcion;
	private int cantidad;
	private int idServicio;
	public void getIdServicio() {
	
	}
	
	public void setIdServicio(Object int id) {
	
	}
	
	public void getId() {
	
	}
	
	public void setId(Object int id) {
	
	}
	
	public void getNombre() {
	
	}
	
	public void setNombre(Object String n) {
	
	}
	
	public void getPrecio() {
	
	}
	
	public void setPrecio(Object int p) {
	
	}
	
	public void getDescripcion() {
	
	}
	
	public void setDescripcion(Object String d) {
	
	}
	
	public void getCantidad() {
	
	}
	
	public void setCantidad(Object int c) {
	
	}
}
