//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Aviso.java
//  @ Date : 17-07-2009
//  @ Author : 
//
//




public class Aviso {
	private String descripcion;
	private Date fecha;
	private int idMascota;
	public void getDescripcion() {
	
	}
	
	public void getFecha() {
	
	}
	
	public void getIdMascota() {
	
	}
	
	public void setDescripcion(Object String d) {
	
	}
	
	public void setIdMascota(Object int id) {
	
	}
	
	public void setFecha(Object Date d) {
	
	}
}
