//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Item.java
//  @ Date : 17-07-2009
//  @ Author : 
//
//




public class Item {
	private Date fecha;
	private Picture fotografia;
	private int idMascota;
	private int idItem;
	public void getFecha() {
	
	}
	
	public void setFecha(Object Date d) {
	
	}
	
	public void getFotografia() {
	
	}
	
	public void setFotografia(Object Picture p) {
	
	}
	
	public void getIdMascota() {
	
	}
	
	public void setIdMascota() {
	
	}
	
	public void getIdItem() {
	
	}
	
	public void setIdItem(Object int i) {
	
	}
}
