//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MantenerMascota.java
//  @ Date : 17-07-2009
//  @ Author : 
//
//




public class MantenerMascota {
	public void addMascota(Object Mascota m) {
	
	}
	
	public void delMascota(Object int m) {
	
	}
	
	public void purgMascota(Object int m) {
	
	}
	
	public void setMascota(Object Mascota m) {
	
	}
	
	public void getMascota(Object int id) {
	
	}
}
