//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MantenerAviso.java
//  @ Date : 17-07-2009
//  @ Author : 
//
//




public class MantenerAviso {
	public void addAviso(Object Aviso a) {
	
	}
	
	public void purgAviso(Object int id) {
	
	}
	
	public void getAviso(Object int id) {
	
	}
}
