//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PostOperatorio.java
//  @ Date : 17-07-2009
//  @ Author : 
//
//




public class PostOperatorio extends Registro {
	private String medicamentoRecetado;
	private String alimentoRecetado;
	private String indicacionMedica;
	private String veterinarioAsociado;
	private String ayudanteAsociado;
	public void getMedicamentoRecetado() {
	
	}
	
	public void getAlimentoRecetado() {
	
	}
	
	public void getIndicacionMedica() {
	
	}
	
	public void getVeterinarioAsociado() {
	
	}
	
	public void getAyudanteAsociado() {
	
	}
	
	public void setMedicamento(Object String m) {
	
	}
	
	public void setAlimento(Object String a) {
	
	}
	
	public void setIndicacion(Object String i) {
	
	}
	
	public void setVeterinario(Object String v) {
	
	}
	
	public void setAyudante(Object String a) {
	
	}
}
