//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PreOperatorio.java
//  @ Date : 17-07-2009
//  @ Author : 
//
//




public class PreOperatorio extends Registro, Registro {
	private String veterinarioAsociado;
	private string ayudanteAsociado;
	private String observacion;
	private String sintoma;
	private String diagnostico;
	public void getVeterinarioAsociado() {
	
	}
	
	public void getAyudanteAsociado() {
	
	}
	
	public void getObservacion() {
	
	}
	
	public void getSintoma() {
	
	}
	
	public void setDiagnostico(Object String d) {
	
	}
	
	public void setAyudanteAsociado(Object String s) {
	
	}
	
	public void setVeterinarioAsociado(Object String v) {
	
	}
	
	public void setObservacion(Object String o) {
	
	}
	
	public void setSintoma(Object String s) {
	
	}
}
